# For more info on HTTP files go to https://aka.ms/vs/httpfile


POST https://localhost:53531/ratings
Content-Type: application/json

{
    "SourceHash": "3f76818f507fe7eb6422bd0703c64c88",
    "SourceXp": 1000,
    "SourceReef": "eu",
    "Targets": [
        {
            "Type": "Negative",
            "TargetHash": "3f76818f507fe7eb6422bd0703c64c88",
            "TargetXp": 500
        }
    ]
}

###

GET https://localhost:53531/ratings
