# For more info on HTTP files go to https://aka.ms/vs/httpfile


POST https://localhost:53531/1/ratings
Content-Type: application/json

{
    "sourceHash": "3f76818f507fe7eb6422bd0703c64c88",
    "sourceLevel": 20,
    "sourceReef": "eu",
    "targets": {
        "0000008006484e0980931833e7ee5a3c": {
            "type": "negative",
            "targetLevel": 30
        },
        "76818f507fe7aaeb6422bd0703c64c88": {
            "type": "positive",
            "targetLevel": 1
        }
    }
}

###

GET https://localhost:53531/1/ratings
