# For more info on HTTP files go to https://aka.ms/vs/httpfile


POST https://localhost:53531/1/ratings
Content-Type: application/json

{
    "SourceHash": "3f76818f507fe7eb6422bd0703c64c88",
    "SourceXp": 1000,
    "SourceReef": "eu",
    "Targets": {
        "0000008006484e0980931833e7ee5a3c": {
            "Type": "Negative",
            "TargetXp": 500
        },
        "76818f507fe7aaeb6422bd0703c64c88": {
            "Type": "Positive",
            "TargetXp": 1000
        }
    }
}

###

GET https://localhost:53531/1/ratings
